# Generated by Django 4.2.5 on 2023-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dificulty',
            field=models.ManyToManyField(to='main1.dificulty'),
        ),
    ]
