# Generated by Django 4.2.7 on 2023-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_customer_dificulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='testing@angrybird.com', max_length=300),
        ),
    ]
