# Generated by Django 4.2.7 on 2023-11-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
