# Generated by Django 4.2.7 on 2023-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=300, upload_to='\\static\\media'),
        ),
    ]
