# Generated by Django 4.2.7 on 2023-12-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_dificulty_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dificulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.dificulty'),
        ),
    ]
