# Generated by Django 4.2.7 on 2023-11-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_customer_dificulty'),
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dificulty',
            name='customer',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='game.customer'),
        ),
    ]
