# Generated by Django 4.2.7 on 2023-11-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0003_alter_dificulty_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dificulty',
            name='customer',
        ),
    ]
