# Generated by Django 4.2.7 on 2023-12-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0004_remove_dificulty_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dificulty',
        ),
    ]
